
import { Card, CategoryType } from './types';

export const INITIAL_CARDS: Card[] = [
  // Tất cả các lá bài được gộp chung vào 1 category duy nhất
  { id: 'v1', title: 'Vẽ Mặt', content: 'Để người bên trái vẽ ria mép lên mặt bạn bằng bút bi hoặc son môi.', penalty: 'Uống 2 ngụm nếu từ chối.', category: CategoryType.UNIVERSAL },
  { id: 'v2', title: 'Hít Đất', content: 'Thực hiện hít đất 10 cái ngay tại chỗ.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v3', title: 'Điệu Con Vịt', content: 'Đứng lên và nhảy điệu "con vịt" quanh bàn nhậu một vòng.', penalty: 'Uống 2 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v4', title: 'Tiếng Động Vật', content: 'Giả làm tiếng một con vật và bắt cả nhóm đoán, không ai đoán được thì bạn uống.', penalty: 'Uống 1 ly.', category: CategoryType.UNIVERSAL },
  { id: 'v5', title: 'Giọng Vùng Miền', content: 'Nói giọng vùng miền khác (hoặc giọng trẻ con) trong 3 lượt chơi tới.', penalty: 'Quên là uống 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v6', title: 'Biệt Danh Mới', content: 'Để cả bàn đặt cho bạn một biệt danh mới, bạn phải dùng nó đến hết buổi.', penalty: 'Quên không dùng biệt danh tự phạt 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v7', title: 'Găng Tay Tất', content: 'Tháo tất (vớ) và đeo vào tay như găng tay trong 5 phút.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v8', title: 'Thăng Bằng', content: 'Thử thách giữ thăng bằng một chiếc cốc trên đầu trong vòng 1 phút.', penalty: 'Làm rơi là uống hết cốc.', category: CategoryType.UNIVERSAL },
  { id: 'v9', title: 'Tạo Kiểu Tóc', content: 'Để người bên trái tạo kiểu tóc mới cho bạn bằng thun hoặc kẹp tóc.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v10', title: 'Diễn Tả Phim', content: 'Diễn tả một bộ phim nổi tiếng bằng hành động để cả nhóm đoán.', penalty: 'Không ai đoán được uống 2 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v11', title: 'Nhìn Nhau', content: 'Cầm tay người ngồi đối diện và nhìn sâu vào mắt họ trong 1 phút không cười.', penalty: 'Ai cười trước uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v12', title: 'Mặc Áo Ngược', content: 'Mặc áo ngược (mặt trước ra sau) cho đến khi kết thúc trò chơi.', penalty: 'Uống 2 ly bia.', category: CategoryType.UNIVERSAL },
  { id: 'v13', title: 'Viết Lên Trán', content: 'Để người bên phải dùng bút viết một chữ lên trán của bạn.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v14', title: 'Bật Nhảy', content: 'Thực hiện 5 lần bật nhảy (Jumping Jacks) ngay lập tức.', penalty: 'Uống 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v15', title: 'Cù Lét', content: 'Để người khác cù lét vào nách bạn trong 5 giây.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v16', title: 'Yoga', content: 'Uống 1 shot và thực hiện tư thế yoga "cái cây" trong 30 giây.', penalty: 'Ngã là uống thêm 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'v17', title: 'Rap Văn Bản', content: 'Đọc rap một đoạn văn bản bất kỳ (ví dụ: hướng dẫn sử dụng trên vỏ chai).', penalty: 'Uống 2 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'v18', title: 'Cấm Nói', content: 'Thử thách không được nói từ "Tôi/Tớ/Em" trong 3 vòng.', penalty: 'Sai một lần uống 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'a1', title: 'Mượn Điện Thoại', content: 'Cho người đối diện mượn điện thoại 2 phút để đọc bất kỳ tin nhắn nào họ muốn.', penalty: 'Uống 100% ly.', category: CategoryType.UNIVERSAL },
  { id: 'a2', title: 'Check Zalo', content: 'Đọc to 3 tin nhắn gần nhất trong Zalo của bạn.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a3', title: 'Ngồi Vào Lòng', content: 'Ngồi vào lòng người cùng giới bên cạnh trong vòng 2 lượt chơi.', penalty: 'Uống 1 ly đầy.', category: CategoryType.UNIVERSAL },
  { id: 'a4', title: 'Số Dư Tài Khoản', content: 'Cho một người trong bàn xem số dư tài khoản ngân hàng của bạn.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a5', title: 'Lịch Sử Tìm Kiếm', content: 'Để người khác kiểm tra danh sách tìm kiếm gần nhất trên Google/Youtube của bạn.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a6', title: 'Phim Người Lớn', content: 'Kể về lần đầu tiên bạn biết "phim người lớn" là khi nào.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a7', title: 'Top 3 Phim', content: 'Kể tên 3 bộ phim "nóng" mà bạn từng xem.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a8', title: 'Album Ẩn', content: 'Cho người bên cạnh xem ảnh gần nhất trong Album ảnh "Bị ẩn/Đã xóa".', penalty: 'Uống 2 ly bia.', category: CategoryType.UNIVERSAL },
  { id: 'a9', title: '5 Hãng Bao Cao Su', content: 'Kể tên 5 hãng bao cao su trong vòng 10 giây.', penalty: 'Không kể được uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a10', title: '3 Người Ghét', content: 'Kể tên 3 người bạn từng cảm thấy "ghét" trong bàn này.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a11', title: 'Người Yêu Lý Tưởng', content: 'Mô tả người yêu lý tưởng của bạn bằng cách vẽ lên giấy hoặc không khí.', penalty: 'Uống 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'a12', title: 'Trang Điểm', content: 'Để người bên phải trang điểm cho bạn bằng đồ ăn hoặc đồ uống có trên bàn.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'a13', title: 'Tỏ Tình Đồ Vật', content: 'Tỏ tình với một đồ vật bất kỳ trong phòng (cái ghế, cái chai).', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd1', title: 'Nhắn Tin Ex', content: 'Nhắn tin cho người yêu cũ: "Tự nhiên thấy nhớ..." rồi im lặng 5 phút.', penalty: 'Uống 5 shot liên tiếp.', category: CategoryType.UNIVERSAL },
  { id: 'd2', title: 'Gọi Số Lạ', content: 'Gọi điện cho một số ngẫu nhiên trong danh bạ và hát bài "Chúc mừng sinh nhật".', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd3', title: 'Story Mặt Xấu', content: 'Chụp ảnh selfie mặt xấu nhất và đăng lên Story Facebook/Instagram trong 1 giờ.', penalty: 'Uống 4 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd4', title: 'Gọi Cho Mẹ', content: 'Gọi điện cho mẹ và nói "Con yêu mẹ" rồi cúp máy ngay không giải thích.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd5', title: 'Đá Lạnh Trong Áo', content: 'Cho viên đá lạnh vào trong áo và giữ nó cho đến khi tan hết.', penalty: 'Uống 2 ly bia.', category: CategoryType.UNIVERSAL },
  { id: 'd6', title: 'Nhắn Tin Sếp', content: 'Nhắn tin cho sếp/giáo viên: "Em thấy hôm nay anh/chị rất ngầu".', penalty: 'Uống 5 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd7', title: 'Hét To', content: 'Đứng ở cửa/ban công và hét to: "Tôi bị khùng rồi!"', penalty: 'Uống 4 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd8', title: 'Nhắn Tin Crush', content: 'Nhắn tin cho Crush: "Tớ có chuyện muốn nói..." sau đó 2 phút mới nhắn "Mà thôi quên rồi".', penalty: 'Uống 5 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd9', title: 'Vay Tiền', content: 'Gọi điện cho bạn thân và vay 500k với lý do "đi cấp cứu" xem họ phản ứng thế nào.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd10', title: 'Status Lấy Vợ', content: 'Đăng status: "Hôm nay mình muốn lấy vợ/chồng quá" lên Facebook.', penalty: 'Uống 5 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd11', title: 'Rượu Hỗn Hợp', content: 'Uống một ly rượu được pha trộn từ 3 loại đồ uống khác nhau trên bàn.', penalty: 'Không uống được thì nghỉ chơi.', category: CategoryType.UNIVERSAL },
  { id: 'd12', title: 'Trúng Số', content: 'Gọi một người bạn và nói "Tớ vừa trúng số!" rồi cúp máy.', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd13', title: 'Nhắn Group Công Ty', content: 'Nhắn tin vào group chat công ty: "Mọi người ơi, em nhớ mọi người quá".', penalty: 'Uống 5 shot.', category: CategoryType.UNIVERSAL },
  { id: 'd14', title: 'Thánh Nhậu', content: 'Thay đổi tên trong Zalo của bạn thành "Thánh Nhậu" trong 24 giờ.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x1', title: 'Uống Không Tay', content: 'Uống một ngụm rượu mà không dùng tay.', penalty: 'Uống thêm 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x2', title: 'Chụp Selfie Xấu', content: 'Chụp ảnh selfie mặt xấu nhất và đăng lên Story FB/IG trong 1 giờ.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x3', title: 'Ăn Chanh/Ớt', content: 'Ăn một muỗng tương ớt hoặc một lát chanh nguyên chất.', penalty: 'Uống 1 ly bia.', category: CategoryType.UNIVERSAL },
  { id: 'x4', title: 'Làm Bạn Cười', content: 'Ngậm một ngụm nước và để người khác làm bạn cười. Nếu phun ra thì uống thêm.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x5', title: 'Hét Tôi Khùng', content: 'Đứng ở cửa/ban công và hét to: "Tôi bị khùng rồi!"', penalty: 'Uống 2 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x6', title: 'Đi Bằng Đầu Gối', content: 'Đi quanh phòng bằng đầu gối và xin lỗi mỗi người bạn gặp.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x7', title: 'Tỏ Tình Ghế', content: 'Tỏ tình với một đồ vật bất kỳ trong phòng (cái ghế, cái chai).', penalty: 'Uống 1 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'x8', title: 'Đứng 1 Chân', content: 'Đứng một chân và uống hết một shot.', penalty: 'Ngã là uống thêm 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x9', title: 'Rót Rượu', content: 'Giả vờ làm người phục vụ và đi rót rượu cho tất cả mọi người trong bàn.', penalty: 'Uống 1 ngụm với mỗi người.', category: CategoryType.UNIVERSAL },
  { id: 'x10', title: 'Nhảy TikTok', content: 'Nhảy theo một bài nhạc TikTok đang hot nhất hiện tại.', penalty: 'Uống 2 ngụm.', category: CategoryType.UNIVERSAL },
  { id: 'x11', title: 'Số Dư Bank', content: 'Cho một người trong bàn xem số dư tài khoản ngân hàng của bạn.', penalty: 'Uống 3 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x12', title: 'Kể Tên Phim Nóng', content: 'Kể tên 3 bộ phim "nóng" mà bạn từng xem.', penalty: 'Uống 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x13', title: 'Xoay 5 Vòng', content: 'Uống một ly rượu và sau đó phải xoay 5 vòng tại chỗ.', penalty: 'Ngã là uống thêm 1 shot.', category: CategoryType.UNIVERSAL },
  { id: 'x14', title: 'Ngồi Dưới Đất', content: 'Ngồi dưới đất chơi trong vòng 3 lượt tiếp theo.', penalty: 'Uống 1 ly.', category: CategoryType.UNIVERSAL }
];
